parse-community/Parse-SDK-JS

package.json

Include PATENTS file in node.js package

---

src/ParseUser.js
src/__tests__/ParseUser-test.js

Allow disabling current user once it has been enabled
Pass ParseUser to Backbone-style error callback

Allow login (without touching current user) on server env

---

src/ParsePromise.js

This is my bad. This should have been in #115

Updating doc comment for updated 'when' format

---

src/ParseObject.js

should precede setting className
#139

bugfix object clone() method

---

src/ParseUser.js
src/__tests__/ParseUser-test.js

Reject login when invalid username or password type is provided

---

README.md
src/Parse.js

Allows to prevent require warnings.

---

package.json

Updates to **3.3.1** to meet node security guidelines.

Update ws to 3.3.1

---

src/StorageController.react-native.js

Reverts parse-community/Parse-SDK-JS#504

Revert "Adding support for RN 0.50+"

---

integration/cloud/main.js
integration/server.js
integration/test/ParseCloudTest.js
integration/test/ParseQueryAggregateTest.js
src/Cloud.js
src/CoreManager.js
src/RESTController.js
src/__tests__/Cloud-test.js
src/__tests__/CoreManager-test.js
src/__tests__/RESTController-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/486

Add Jobs Functions to Cloud

---

README.md

Easily accessible link to the API Reference latest release

Add API Reference link to README

---

package.json

fix(package): update ws to version 6.0.0

---

package.json

chore(package): update codecov to version 3.0.4

---

gulpfile.js
package-lock.json
package.json

@dplewis hope this will help you, check this branch out and let me know if it does what your're expecting.

Adds ability to watch the build

---

src/RESTController.js
src/__tests__/RESTController-test.js

@dplewis this will fix the issue when the header is not present as it's not whitelisted from the server.

Check if job header is present

---

jsdoc-conf.json
package-lock.json
package.json

Updates docs generation template

---

src/LiveQueryClient.js
src/LiveQuerySubscription.js
src/__tests__/LiveQueryClient-test.js

https://github.com/parse-community/parse-server/pull/5265
Let me know if more tests are needed

Add original object to LiveQuery events

---

integration/test/ParseFileTest.js
src/ParseFile.js
src/__tests__/ParseFile-test.js

Superced: https://github.com/parse-community/Parse-SDK-JS/pull/465
uri vs url?

File upload via uri

---

integration/test/ParseUserTest.js
src/ParseUser.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/263
Let me know if anything should be added

UserSubclass.logIn and UserSubclass.signUp returns subclass

---

integration/test/ParseUserTest.js

1. test loggin in with the js sdk to verify documentation change
2. add a negative test that proves we need the master key to link

Add two unit tests for linking

---

package-lock.json
package.json

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/797

Update uuid to the latest version 🚀

---

CHANGELOG.md
package-lock.json
package.json
src/__tests__/LocalDatastore-test.js
src/__tests__/Parse-test.js

Bump eslint-plugin-flowtype to 3.6.1
Suppress console in test logs for readability

⚡️ Release v2.4.0

---

integration/test/ParseLocalDatastoreTest.js
src/OfflineQuery.js

Can query from Date Object / Date String comparison

LDS: Improve querying dates

---

CHANGELOG.md
package-lock.json
package.json

Sorry I accidently added a commit directly to master.
https://github.com/parse-community/Parse-SDK-JS/commit/64f359af251ccb9473f4464d09bf3ba8a0d12dc9

⚡️ Release v2.6.0

---

README.md

Makes the guide easily accessible.

Add Cloud Code guide to README

---

CHANGELOG.md
package-lock.json
package.json

Pending: https://github.com/parse-community/Parse-SDK-JS/pull/951, https://github.com/parse-community/Parse-SDK-JS/pull/956

⚡️ Release v2.8.0

---

CHANGELOG.md
package-lock.json
package.json

Wow! I didn't realize how big this release was.

⚡️ Release v2.9.0

---

CHANGELOG.md
package-lock.json
package.json

⚡️ Release v2.9.1

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/ParseQuery.js

Fixes Logo in ReadME.
Fixes Audit by updating dev dependencies.

⚡️ Release v2.11.0

---

src/ParseUser.js
src/__tests__/ParseUser-test.js
src/__tests__/test_helpers/mockAsyncStorage.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1052

Fix user.become for AsyncStorage

---

.travis.yml
README.md
gulpfile.js
package-lock.json
package.json
src/CryptoController.js

Close https://github.com/parse-community/Parse-SDK-JS/issues/1092

Fix react-native build

---

src/ParseObject.js
src/__tests__/ParseFile-test.js

Similar to https://github.com/parse-community/Parse-SDK-JS/issues/1106

Pass SaveAll options to Files

---

CHANGELOG.md
package-lock.json
package.json

I know it has been a while since the last release. A lot of great features in this one!

⚡️ Release v2.12.0

---

src/ParseQuery.js
src/__tests__/ParseQuery-test.js

fix read preference for aggregate query

---

CHANGELOG.md
package-lock.json
package.json

⚡️ Release 2.15.0

---

src/ParseQuery.js

Add missing modifier docs for matches query.

fix(docs): Matches Modifier Documentation

---

integration/server.js

I don't know the proper way to fix this but I receive this error randomly when I run the test suite. Sometimes it happens once, sometimes 10 times in a row. Has anyone else encountered this?
P.S. I've had this error for a long long time.

fix(test): Flaky Tests

---

CHANGELOG.md
package-lock.json
package.json

⚡️ Release 2.16.0

---

CHANGELOG.md
build_releases.js
gulpfile.js
package-lock.json
package.json

Most of the fixes are from https://github.com/parse-community/Parse-SDK-JS/pull/1241
Improves build speed by ~20 seconds, from 29.6s -> 12.2s on my machine.

⚡️ Release 2.18.0

---

src/ParseError.js

[Related to this PR](https://github.com/parse-community/parse-server/pull/6977)

Error codes for MFA

---

src/ParseUser.js
src/__tests__/ParseUser-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1283

Change default login method to POST

---

CHANGELOG.md
package-lock.json
package.json

A lot of new additions and a breaking change in this one. First release of the New Year

⚡️ Release 3.0.0

---

src/__tests__/weapp-test.js

Add test case for https://github.com/parse-community/Parse-SDK-JS/pull/1356
Related issue: #`FILL_THIS_OUT`

chore(WeChat): Add missing uuid test
