parse-community/Parse-SDK-JS

src/FacebookUtils.js

There was a javascript error that caused FacebookUtils.authenticate to crash and made login with Facebook impossible since v1.6.0.
Fixes https://developers.facebook.com/bugs/882121675197813/

Fix Facebook login error

---

src/ParseObject.js
src/__tests__/ParseObject-test.js

objects should only be encoded with flat pointers, not inflated objects. This adds a test that fails without this change.

Avoid recursion on encoding circular pointers

---

src/ParseObject.js

The function documentation on some `Parse.Object` methods refers to Backbone-specific behavior that was removed from the JS SDK in version 1.6.0.  This removes those references.

Fix outdated comments

---

src/ParseObject.js
src/__tests__/ParseObject-test.js

Optimistically set ACLs from JSON blobs

---

src/ParseQuery.js
src/__tests__/ParseQuery-test.js

Perform user rewrite on Parse.Query

---

src/ParseUser.js
src/__tests__/ParseUser-test.js

When `_linkWith` is called recursively, we can not get the error thrown by the not first `_linkWith` call, as mentioned in #12 . This PR fixes this and add a test.

Expose error in _linkWith recursive call

---

src/ParseUser.js
src/__tests__/ParseUser-test.js

Strip anonymous when we set username, even we do not support anonymous user in JS SDK, we may encounter anonymous users created by android/iOS in cloud code, so we need to do this.
Fix issue #13

Strip anonymous when we set username

---

src/ParseObject.js
src/__tests__/ParseObject-test.js

This is an attempt to resolve the first blocker in #73.
Not sure if the Flow typing is correct but I'm sure you'll let me know if it is not.

Add ability to ignore validation on Parse.Object constructor/set()

---

src/ParseUser.js

When calling `Parse.FacebookUtils.init();` from React Native I get this error (Parse v1.6.9)
This pull request fixes it. Not sure how to test if this breaks web behavior in any way.

Make FacebookUtils work with React Native

---

src/ParseQuery.js

the documentation incorrectly tries to use the `success` function when rendering the `objectClass`
this makes the display of the parameter more consistent

Fix documentation parsing error

---

src/ParsePromise.js
src/__tests__/ParsePromise-test.js

Addresses #114 
Basically if you use arguments to pass promises to `Parse.Promise.when`, then use arguments to pass the results to any resulting `then` call. If you use an array, then pass an array to the `then` call

Make sure `when` argument corresponds with `then` arguments

---

src/ParsePromise.js
src/__tests__/ParsePromise-test.js

Reverts ParsePlatform/Parse-SDK-JS#115
Unfortunately, I did not realize that this introduced breaking changes

Revert "Make sure `when` argument corresponds with `then` arguments"

---

src/ParseObject.js
src/__tests__/ParseObject-test.js

It seems we do not handle ACL on save. Normally for a save/update, the server just return `createAt, objectId` and `updateAt`, so it is fine. However, if the developers enable beforeSave for this class, the server will return the full object. In this situation, if we do not handle ACL, it will make `object.getACL()` return `null`.
I follow the way we handle ACL in `_finishFetch` to handle ACL. Not sure it is the best way to do that.

Handle ACL on save

---

src/ParseQuery.js

In the case where you query a relation key on an unfetched object, you don't know the className of the objects you will receive.  The SDK uses the redirectClassNameForKey parameter in the query, and the correct className is provided by the server, but it is being ignored and overwritten by the SDK here.
```javascript
// Setup data model
var Wheel = Parse.Object.extend('Wheel');
var Car = Parse.Object.extend('Car');
var origWheel = new Wheel();
origWheel.save().then(function() {
var car = new Car();
var relation = car.relation('wheels');
relation.add(origWheel);
return car.save();
}).then(function(car) {
// Create an un-fetched shell car object
var unfetchedCar = new Car();
unfetchedCar.id = car.id;
var relation = unfetchedCar.relation('wheels');
var query = relation.query();
// Parent …
```

Updated query result handling to fix querying for unfetched relations

---

src/ParseObject.js

If initialize is used to initialize objects (provide defaults, etc) it should happen before the provided attributes are set on the object and validated, not after.
This attempts to resolve part of the second blocker in #73.

Move invocation of initialize above setting of attributes and validation

---

src/ParsePromise.js
src/__tests__/ParsePromise-test.js

Allows Parse.Promises to be constructed in the ES6 "executor" style, without intervening with old construction.
```js
// Valid:
return new Parse.Promise((resolve, reject) => {
myAsyncFunction((result) => {
resolve(result);
});
});
// Also still valid:
let p = new Parse.Promise();
myAsyncFunction((result) => {
p.resolve(result);
});
return p;
```
cc @grantland

Allow ES6-style Promise construction

---

src/ParseQuery.js
src/__tests__/ParseQuery-test.js

If the target className of a relation is not known ahead of time, and the server does not pass the className back on the raw JSON of Parse Object results, the query results end up with the wrong className.
The className to be used comes back as a top-level key on the query result payload. This diff makes sure that value is used, if available.

Make sure the className is correct for results on unknown relations

---

src/ParseFile.js
src/__tests__/ParseFile-test.js

This is a simple feature, and it would go a long way to have it implemented. Since files on `http://files.parsetfss.com` can also be accessed at `https://files.parsetfss.com`, I was surprised this isn't available yet. Been running into problems using `Parse.File` with images on a site using https, as it throws a Mixed Content warning. There may be a more consistent way to handle the api, but this works fine in my opinion.

Option to specify https for Parse.File url()

---

src/ParseObject.js
src/ParseQuery.js
src/__tests__/ParseObject-test.js

Handles `Object.fetch()` and Query results

Clear old data on fetch

---

src/ParsePromise.js
src/__tests__/ParsePromise-test.js

This adds the remaining APIs necessary to make Parse.Promise fully interchangeable with the ES6 Promise implementation.

Implement Promise.catch, Promise.all, Promise.race

---

src/ParseObject.js
src/UniqueInstanceStateController.js
src/__tests__/ParseObject-test.js
src/__tests__/ParseUser-test.js
src/__tests__/UniqueInstanceStateController-test.js

`ParseObject.prototype.newInstance()` creates a new, memory-unique instance of a Parse Object, as though it had been fetched again from the server. This is only really relevant in Unique Instance mode.

New API for creating a new instance of an object

---

.gitignore
.travis.yml
integration/README.md
integration/package.json
integration/server.js
integration/test/ArrayOperationsTest.js
integration/test/DirtyTest.js
integration/test/IncrementTest.js
integration/test/ParseACLTest.js
integration/test/ParseGeoBoxTest.js
integration/test/ParseGeoPointTest.js
integration/test/ParseMasterKeyTest.js
integration/test/ParseObjectTest.js
integration/test/ParseQueryTest.js
integration/test/ParseRelationTest.js
integration/test/ParseRoleTest.js
integration/test/ParseSubclassTest.js
integration/test/ParseUserTest.js
integration/test/clear.js
run_integration.sh

Integration tests (Rye)

---

package.json
src/CoreManager.js
src/LiveQueryClient.js
src/LiveQuerySubscription.js
src/Parse.js
src/ParseLiveQuery.js
src/ParseQuery.js
src/__tests__/LiveQueryClient-test.js

Live Queries Support.

---

gulpfile.js
package.json
src/EventEmitter.js
src/LiveQueryClient.js
src/LiveQuerySubscription.js
src/ParseLiveQuery.js
src/__tests__/LiveQueryClient-test.js

This should make sure that EventEmitter is properly initialized on every platform and build. The code for parse-latest looks correct, as do the `lib` builds, but please test this thoroughly.

Fix 'events' resolution issue

---

src/LiveQuerySubscription.js
src/ParseLiveQuery.js
src/ParseQuery.js

Updating Parse.LiveQuery to use currentUserAsync.

---

src/ParseLiveQuery.js

The EventEmitter class of React Native does not allow nested events and so, the `query.subscribe()` was not working.

Corrected ParseLiveQuery for react native

---

src/LiveQueryClient.js

In Safari, the WebSocket is typeof Object. This fix enables proper LiveQuery support for some versions of Safari (it appears that Safari Technology Preview handles Websockets a little differently, so this may not be an issue in future versions of Safari).

Fixes Websocket Implementation for Safari

---

src/ParseLiveQuery.js

This allows LiveQueryServer to work over Parse Sever with SSL

Fix LiveQuery SSL

---

src/ParseQuery.js

Hi, it appears Each queries can also accept useMasterKey and sessionToken option but it wasn't documented, this PR is just a minor docs fix.

Update documentation for Each queries.

---

src/ParseObject.js
src/__tests__/ParseObject-test.js

On parse.com, when running a beforeSave hook, if a key is `unset` the change is not propagated to the client. 
On parse-server, we forward this change by setting the `key: {__op: Delete}` that is interpolated by the JS SDK as an UnsetOp.
This proposed PR will set key = undefined in those cases fixing https://github.com/ParsePlatform/parse-server/issues/1840
https://github.com/ParsePlatform/parse-server/pull/1946

Adds ability to interpolate delete operations

---

src/CoreManager.js
src/Parse.js
src/ParseHooks.js
src/__tests__/Hooks-test.js

- Adds hooks API to parse/node in perspective to remove the hooks API from experimental on parse-server
- Will remove Parse.Hooks from parse-server once merged
- Will keep E2E tests in parse-server to make sure the API is compliant
- Tested on parse.com and create/update/remove works perfectly without any changes

Adds Hooks API on parse/node

---

src/ParseACL.js

Got everything working with Flow, then noticed a test was broken. In repairing it, types became unsound. This makes Flow happy again.

Fix typing that was broken to repair tests

---

src/ParseFile.js
src/RESTController.js

See issue #311 for details and discussion.
Maybe test coverage should be improved for this functionality.

closed #311: Parse.File sends incorrect Content-Type to API

---

src/ParseQuery.js
src/__tests__/ParseQuery-test.js

When a query is issued with a select, we know that the object returned will only be part of the truth from the server. The current implementation, on retrieving the results of a query with a select, erases all the information in the shared object except the fields included in the select, which are updated. That's not the best possible estimate of the state of truth on the server.
Ideally, for a query with a select, the cached object should only be updated or erased for the fields involved in the query.
This PR introduces test cases for retrieving previously retrieved objects with a more restrictive select clause in accordance with the above goal, and proposes a code change that fixes the issue and allows these new test cases to pass.
Fixes #371.

Select queries should not erase cached data from unselected fields

---

README.md
src/StorageController.react-native.js
src/__tests__/Storage-test.js

Addressing https://github.com/facebook/react-native/commit/cf1bc8d6443432ba24efa17cd15ba73072fad193

Addresses filename change in react-native library

---

src/ParseError.js
src/__tests__/ParseError-test.js

I noticed that our error logs are filled with thousands of "[Object object]" due to the ParseError object not having a sensible string representation. Errors ripple down to the Express.js error log handler, which calls `console.error(err.stack || err.toString())`. In our case, these are typically `209 Invalid session token` errors, as we just migrated to using revocable sessions. The proposed fix in this pull request is to add a `toSting()` method for ParseErrors.

Add sensible string representation of ParseError objects

---

src/ParseLiveQuery.js
src/__tests__/ParseLiveQuery-test.js

When you call `subscribe()` on a query (which goes through the ParseLiveQuery controller), the resulting subscription does not currently receive `close` or `error` events for the underlying connection. This was occurring because the LiveQueryController is wrapping the underlying subscriptions, and was not forwarding the `close` or `error` events.
This pull request correctly wraps these two event types so that subscriptions receive all the event notifications they are supposed to, and introduces a new test case to check that all subscription events are forwarded correctly.

ParseLiveQuery controller should wrap all subscription events

---

src/ParseFile.js

Without this, we are getting unauthorized messages when saving base64 files.

ParseFile & useMasterKey: pass options through to RESTController from saveBase64

---

src/__tests__/ParseFile-test.js

Not sure how widespread of a problem this is, but I recently submitted a PR for ParseFile and noticed that some of the tests for it were not handling async properly and weren't actually executing assertions.  This PR addresses ParseFile's tests only.

Fix async tests in ParseFile-test.js

---

.gitignore
integration/package.json
integration/test/ParseGeoPointTest.js
src/ParseQuery.js

I added support for querying within polygon on the latest server update
https://github.com/parse-community/parse-server/pull/3866
Let me know if I should add more tests.
Sometimes errors when I run test I get a lot of these errors
```
Error: timeout of 5000ms exceeded. Ensure the done() callback is being called in this test.
```
I don't think my objects are getting delete before and after each it() test

Added WithinPolygon to Query

---

src/ParseQuery.js
src/__tests__/ParseQuery-test.js

Made mistake with previous PR. This is new one.
Method restores query from json gained from Parse.Query.toJSON()

Parse.Query.fromJSON method

---

README.md

Just a small fix of `https` to `http` for the JS guide link, which is only available over `http`.

Corrects Guide Link in README.md

---

README.md
integration/package.json
integration/test/ParseGeoPointTest.js
integration/test/ParseObjectTest.js
integration/test/ParsePolygonTest.js
src/Parse.js
src/ParseObject.js
src/ParsePolygon.js
src/ParseQuery.js
src/__tests__/ParseObject-test.js
src/decode.js
src/encode.js

New Polygon Type and new Query for finding all polygons that contains a point
https://github.com/parse-community/parse-server/pull/3944
Waiting for 2.6.0 release

Add Type Polygon to Schema and PolygonContains to query

---

src/StorageController.react-native.js

Adding fix, as posted on [#496](https://github.com/parse-community/Parse-SDK-JS/issues/496)

Adding support for RN 0.50+

---

.gitignore
.travis.yml
jsdoc-conf.json
package.json
src/Analytics.js
src/Cloud.js
src/CoreManager.js
src/FacebookUtils.js
src/LiveQueryClient.js
src/LiveQuerySubscription.js
src/Parse.js
src/ParseACL.js
src/ParseConfig.js
src/ParseError.js
src/ParseFile.js
src/ParseGeoPoint.js
src/ParseLiveQuery.js
src/ParseObject.js
src/ParsePolygon.js
src/ParsePromise.js
src/ParseQuery.js
src/ParseRelation.js
src/ParseRole.js
src/ParseSession.js
src/ParseUser.js
src/Push.js
src/escape.js

This PR fixes a few issues when generating docs with JS docs, See the generated docs here:
https://flovilmart.github.io/parse-js-docs-demo/index.html
If we're all ok with it, I'll push to the gh-pages branch and automate the release on tags.

Fixes jsdoc generation, adds jsdoc support

---

.travis.yml
integration/package.json
integration/test/ParseQueryAggregateTest.js
src/CoreManager.js
src/ParseQuery.js
src/__tests__/CoreManager-test.js
src/__tests__/ParseQuery-test.js

Support for `distinct()` and `aggregate()` queries.
Pending: https://github.com/parse-community/parse-server/pull/4207

Support for Aggregate Queries

---

.travis.yml
integration/package.json
integration/test/ParseSchemaTest.js
src/CoreManager.js
src/Parse.js
src/ParseSchema.js
src/__tests__/CoreManager-test.js
src/__tests__/ParseSchema-test.js

Pending: https://github.com/parse-community/parse-server/pull/4240
Adds CRUD support for new Parse.Schema class.

Support for Parse Schema

---

src/LiveQueryClient.js

Use field keys specified via query.select() as fields value for subscribe.
Default fields of [className,objectId, createdAt, updatedAt, ACL] are always sent by server, which means the LQ subscribe message description for query.fields is inaccurate.
https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification#subscribe-message
I don't think ACL should be in the default fields but I don't know yet if it's used in the client somehow.  Looking at that is another task.

Support fields in Live Query subscriptions

---

.travis.yml
src/CoreManager.js
src/Parse.js
src/StorageController.react-native.js
src/__tests__/Storage-test.js

closes #508
closes #496
closes #418
closes #515
And once and for all all ReactNative async storage issues!

Adds interface to externally set RN Async Storage

---

integration/package.json
integration/test/ParseQueryTest.js
src/ParsePolygon.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js
src/__tests__/ParseSchema-test.js

Supersed: https://github.com/parse-community/Parse-SDK-JS/pull/470
Closes: https://github.com/parse-community/parse-server/issues/4490, https://github.com/parse-community/Parse-SDK-JS/issues/476
To be used with Parse-Server 2.5.0+
* Fixed docs typos
* Lint Test files
* Remove unnecessary code from past tests
* Bump parse-server to 2.7.1

Support for Full Text Search Query

---

integration/test/ParseSchemaTest.js
src/CoreManager.js
src/ParseError.js
src/ParseSchema.js
src/__tests__/CoreManager-test.js
src/__tests__/ParseSchema-test.js

This adds the purge method to ParseSchema. This allows the deletion of all objects without having to run through and query all objects for removal. This was added to ParseSchema as the related delete method requires the class to be first empty of objects.
Polygon type support has also been added to ParseSchema, both via a supported method to add a polygon type field and as a recognized field when asserting types.

Adds Purge & Polygon to Parse.Schema

---

src/ParseFile.js
src/__tests__/ParseFile-test.js

The regex to extract the components from a base64 encoded string doesn't handle mime types which contain a number, e.g. audio/m4a.
It was failing with the error:
TypeError: Cannot read property '1' of null
at ParseFile (/app/node_modules/parse/lib/node/ParseFile.js:121)
The regex has been updated to allow numbers, and a test added which failed before the change.

Update ParseFile to handle a data URI containing a number

---

src/ParseFile.js

Make javascript key optional

---

integration/package-lock.json
integration/package.json
integration/test/ParseGeoPointTest.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

Adding convenience methods for queries with `geoWithin.nearSphere`.
Depending on https://github.com/parse-community/parse-server/pull/4825

Add nearsphere convenience methods

---

src/ParseQuery.js

Users shouldn't expect an undefined when calling get.

Insist on the difference between 'first' and 'get'

---

src/ParseFile.js

Currently, for me, the [ParseFile](http://parseplatform.org/Parse-SDK-JS/api/v1.11.1/Parse.File.html) Constructor API docs has a <pre> tag that is not rendering:
this fix, while not ideal, is a good improvement.
I'm game to try someother approaches?

Fix for the formatting of the ParseFile comment that has

---

src/ParseQuery.js

These both can accept either a string, or an array of strings

Fix documentation for include and select

---

src/ParseFile.js
src/__tests__/ParseFile-test.js

Before this PR: 
```javascript
var parseFile = new Parse.File('filename', file);
parseFile.save().then((f)=>{
console.log(f.toJSON())  // {__type: "File", name: undefined, url: undefined}
});
```
i think it is a bug and related this issue: #558 
RESTController.ajax method was return with ```response``` object, you can see that Implementation in [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/RESTController.js#L55) and [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/RESTController.js#L114)

Fix Parse File upload problem via ajax

---

2.0.0.md
CHANGELOG.md
README.md
package.json
src/CloudCode.js

This PR does a few things:
1. fix the issue with the headers, when running with an older parse-server
2. updates the documentations for Cloud Code for parse-server 3.0. This is not ideal that the Cloud Code docs isn't in parse-server itself, but that's how it is, perhaps we could do something about it like a like or I dunno

:zap: Release v2.0.1

---

integration/test/ParseQueryTest.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

https://github.com/parse-community/parse-server/pull/4838
provides shorthand for include('*')

Support includeAll Query

---

2.0.0.md

Whereas `Parse.Promise.always`, `Promise.finally` callback don't receive any arguments, and don't resolve with a new argument to pass to the next promise in chain.

Add a warning in 2.0.0.md about Promise.finally

---

integration/test/ParseQueryTest.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

https://github.com/parse-community/parse-server/pull/4766
Might have to change the name and the documentation for this one.

Support containedBy Query

---

integration/test/ParseQueryTest.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

https://github.com/parse-community/parse-server/pull/4768

Support nor Query

---

integration/test/ParseObjectTest.js
integration/test/ParseUserTest.js
src/ParseObject.js
src/ParseUser.js
src/RESTController.js
src/__tests__/ParseObject-test.js
src/__tests__/ParseUser-test.js

Added `fetchWithInclude` and `fetchAllWithInclude` to Parse Object.
Added `fetchWithInclude` to User
As discussed https://github.com/parse-community/parse-server/pull/4845#issuecomment-398895529

Support Fetch With Include

---

integration/test/ParseQueryAggregateTest.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

Instead of converting array to json for the payload just pass it though.
Since I can't pass an array to the RESTController, The pipeline key needs to be added to the server for this to work.

Allow aggregate stages with same name

---

src/ParseObject.js

I couldn't find any trace of this 'wait' option in the code (sdk or server)

Removal of the 'wait=true" comment in destroy

---

src/LiveQueryClient.js
src/__tests__/LiveQueryClient-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/372, https://github.com/parse-community/Parse-SDK-JS/issues/340, https://github.com/parse-community/Parse-SDK-JS/issues/595

LiveQuery Support for Subclasses

---

src/ParseGeoPoint.js
src/__tests__/ParseGeoPoint-test.js

Validate if GeoPoint values is number

---

integration/cloud/main.js
integration/test/ParseCloudTest.js
src/Cloud.js
src/__tests__/Cloud-test.js

Closes https://github.com/parse-community/Parse-SDK-JS/issues/417
Based on discussion https://github.com/parse-community/parse-server/issues/5053
Previously threw Invalid response and unhandled promise rejection

Handle undefined in Cloud Code

---

src/CoreManager.js
src/ParseConfig.js
src/__tests__/CoreManager-test.js
src/__tests__/ParseConfig-test.js

Allow to use `.save()` on Parse.Config when a masterKey is defined to avoid the use of `Parse._request` #684

Save Method for Parse.Config

---

src/LiveQueryClient.js
src/__tests__/LiveQueryClient-test.js

Addresses https://github.com/parse-community/parse-server/issues/4998

LiveQuery handle unset operation

---

integration/test/ParseLocalDatastoreTest.js
src/LiveQueryClient.js
src/ParseObject.js
src/__tests__/LiveQueryClient-test.js
src/__tests__/ParseObject-test.js

Since the update / event subscription is the latest version of an object we should update the server data and localDatastore. Per [discussion](https://github.com/parse-community/Parse-SDK-JS/pull/714#issuecomment-451615779)
Added a isPinned helper to LDS.

LiveQuery override data on update

---

.travis.yml
CHANGELOG.md
package.json

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/715
I removed `preintegration` from `.travis.yml`, If we are running gulp-watch no need to rebuild the entire SDK every time for integration testing.
A lot of goodies in this one!

:zap: Release v2.2.0

---

gulpfile.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/717
If you are in a project that doesn't have a global `regeneratorRuntime` defined i.e Browser an error is thrown.
This fix causes babel to use `@babel/runtime/regenerator` instead of a global variable.
`regenerator` is used whenever async / generator functions are used
Thanks @agoldis

(fix) regeneratorRuntime is not defined

---

CHANGELOG.md
package.json

Fixes a critical issue that makes Parse unusable for some users.

:zap: Release v2.2.1

---

src/FacebookUtils.js

Base on this issue https://github.com/parse-community/Parse-SDK-JS/issues/726
I'm not sure what is the usage for `newOptions.authResponse` in this library. So I remove the line that assign `authResponse` to `newOptions`.
Anyone feel free to comment.

remove assign authResponse in FB.init

---

integration/test/ParseUserTest.js
src/AnonymousUtils.js
src/CoreManager.js
src/Parse.js
src/ParseObject.js
src/ParseUser.js
src/__tests__/AnonymousUtils-test.js
src/__tests__/ParseUser-test.js

Also fixed issue with sessionToken not being passed when saving users.

Support for Anonymous Users

---

CODE_OF_CONDUCT.md

As flovilmart is no longer a core maintainer his email is being removed in favour of admin@parseplatform.org (as agreed with @acinader).

Remove flovilmart's email from COC

---

integration/server.js
integration/test/ParseLiveQueryTest.js
integration/test/helper.js
src/CoreManager.js
src/LiveQueryClient.js
src/LiveQuerySubscription.js
src/ParseLiveQuery.js
src/ParseQuery.js
src/__tests__/ParseLiveQuery-test.js
src/__tests__/ParseQuery-test.js

Fixes LiveQuery behavior on multiple subscriptions

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/CloudCode.js
src/LocalDatastoreController.browser.js
src/ParseLiveQuery.js
src/__tests__/LocalDatastore-test.js

Closes: #687, #670, #723, #669
* Pin packages
* (Jest) Fix deprecated setupTestFrameworkScriptFile
* (Codecov) Fix coverage folders
* Update Parse.Cloud.define docs
* Add discource badge to Readme
* Add @types/parse

⚡️ Release v2.3.0

---

src/ParseFile.js
src/__tests__/ParseFile-test.js

`http` and `https` modules don't exist in browser

(Browser) Support for File Uri Upload

---

integration/server.js
integration/test/CustomAuth.js
integration/test/ParseUserTest.js
src/ParseObject.js
src/ParseUser.js
src/__tests__/ParseUser-test.js

1. without the master key it is not possible to link a user with an auth provider in cloud code
2. remove a recent addition to pass the sessionToken which was added for anonymous auth, but not necessary and causing problems.  Also remove the related test.

Add options to _linkWith(provider) for masterKey

---

src/ParseObject.js

The documentation for the params required for Object's save method describes 1 param (options), but you cannot actually pass just options as an object to the save method. The correct use of the save method is described with examples in the documentation, but the additional 2 params are not documented. As the save method does accept 3 arguments (in the code as value: function (arg1, arg2, arg3) {), these params need to be added to the documentation and not just mentioned in the examples.

Fixed object save method params documentation

---

integration/server.js
integration/test/ParseUserTest.js
src/FacebookUtils.js
src/__tests__/FacebookUtils-test.js

Improve documentation for `link` and `logIn`. Minor clean up
Improves coverage (no tests exists)
Flow types will be in a separate PR.

Add test cases for FacebookUtils

---

integration/test/ParseACLTest.js
src/__tests__/ParseLiveQuery-test.js

* Fixes unhandled promise rejection in LiveQuery-tests
```
(node:5669) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'send' of undefined
(node:5669) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). 
```
* ParseACLTest weren't waiting for Parse.User.logOut, there were so many I decided to rewrite the tests
```
Failures:
1) Parse.ACL allows logged in get
Message:
Unhandled promise rejection: ParseError: 101 Object not found for delete.
Stack:
error properties: Object({ code: 101 })
Error: Object not found for delete.
at /home/travis/build/parse-community/Parse-SDK-JS/lib/node/RESTController.js:324:19
at …
```

Fix flaky tests

---

src/Cloud.js
src/CoreManager.js
src/InstallationController.js
src/LocalDatastore.js
src/LocalDatastoreController.browser.js
src/LocalDatastoreController.react-native.js
src/ParseConfig.js
src/ParseFile.js
src/ParseObject.js
src/ParsePolygon.js
src/ParseQuery.js
src/ParseSession.js
src/ParseUser.js
src/Storage.js
src/parseDate.js

I believe we can break this up into multiple PR's
This PR covers half of the flow errors (out of 375) without functionality changes.
The next half will need to be reviewed with a fine tooth comb

Improve Flow Layout

---

integration/test/ParseLiveQueryTest.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

Adds sessionToken parameter to `query.subscribe()`
As described in the guide for Advanced API https://docs.parseplatform.org/js/guide/#sessiontoken
This is also a failing test for https://github.com/parse-community/Parse-SDK-JS/issues/778

LiveQuery subscribe with sessionToken

---

integration/server.js
integration/test/ParseLocalDatastoreTest.js
package-lock.json
src/LocalDatastore.js
src/ParseQuery.js
src/__tests__/LocalDatastore-test.js
src/__tests__/ParseQuery-test.js

Closes: #792
Saves `_localId` into the LocalDatastore to keep consistency when querying.

 LDS: Improve pinning unsaved objects

---

src/interfaces/AuthProvider.js

Authentication Provider Interface

---

integration/server.js
integration/test/ParseUserTest.js
src/ParseUser.js
src/__tests__/ParseUser-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/770
Registers a basic auth provider if one doesn't exist.
Users won't have to implement their own Authentication Flow that was required and undocumented before.
Adds test case for linking with twitter

Support _linkWith if no provider exists

---

.gitattributes
CONTRIBUTING.md
package-lock.json
package.json

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/819
* Add .gitattributes file to default to LF line ending
* Add cross-env to handle env variables
* Default watch to browser and added the following commands:
`npm run watch:node`
`npm run watch:browser`
`npm run watch:react-native`
@oallouch Can you try out this branch? I believe with watch, test, and integration should be enough to start contributing.

Support testing on Windows

---

src/ParseObject.js

This PR fixes and adds some JSDocs return types to `ParseObject`'s methods that returns the same as the `set` method. Fixes #830

Fix JSDocs return types of ParseObject's methods

---

src/ParseFile.js

`File` is a subclass of `Blob` and thus this will still accept any `File` as before.
The benefit of also allowing `Blob` is that those are user-creatable, and you can get them from a `Canvas` if you are e.g. resizing images in the browser before uploading them.

Allow any Blob to be uploaded

---

integration/test/ParseUserTest.js
src/ParseObject.js
src/RESTController.js
src/__tests__/ParseUser-test.js
src/__tests__/RESTController-test.js

Fix Facebook login so it properly distinguishes between new and existing users.

---

src/ParseQuery.js
src/__tests__/ParseQuery-test.js

See https://github.com/parse-community/parse-server/issues/5515

Including read preference options in parse query

---

integration/test/ParseObjectTest.js
package-lock.json
src/ParseObject.js
src/__tests__/ParseObject-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/851
Checks if an object has been fetched from the server or not.

Support isDataAvailable

---

integration/test/ParseGeoPointTest.js
integration/test/ParseQueryTest.js
integration/test/ParseUserTest.js
package-lock.json
package.json
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/839
As described [here](https://github.com/parse-community/parse-server/pull/5737)
*package-lock.json bumped to latest master branch of parse-server

Support query exclude keys

---

integration/test/ParseUserTest.js
src/AnonymousUtils.js
src/ParseUser.js
src/__tests__/AnonymousUtils-test.js

This PR also addresses an issue.
```
const user1 = await Parse.User.signUp('anon-not', '1234'); // is current user
const user2 = await Parse.AnonymousUtils.logIn(); // request are made with user1 sessionToken
user2.set('foo', 'bar');
// user2 doesn't have a sessionToken because of https://github.com/parse-community/parse-server/pull/5801
// LinkWith sessionToken won't generate new session token
user2.save();
```

Add options for AnonymousUtils

---

gulpfile.js

Getting this warning over and over again in my [Next.JS](https://nextjs.org/) project:
It looks like you're using the browser version of the SDK in a node.js environment. You should require('parse/node') instead.
Was driving me a bit crazy, as I most certainly do have `SERVER_RENDERING=1` set for my app. I've confirmed this via `console.log()` directly before the `Parse.Initialize()` call.
Looking at my `./node_modules/parse/lib/browser/Parse.js` shows this (odd) line:
if ("browser" === 'browser' && _CoreManager.default.get('IS_NODE') && !undefined) {
...
Given that it's most definitely being written correctly [here](https://github.com/parse-community/Parse-SDK-JS/blob/master/src/Parse.js#L34), I was able to track it down to the slightly misconfigured [env transform …

Fix disappearing SERVER_RENDERING env var

---

.eslintrc.json
README.md
build_releases.sh
gulpfile.js
package-lock.json
package.json
src/LiveQueryClient.js
src/LocalDatastore.js
src/LocalDatastoreController.weapp.js
src/Parse.js
src/ParseFile.js
src/RESTController.js
src/Socket.weapp.js
src/Storage.js
src/StorageController.weapp.js
src/Xhr.weapp.js
weapp.js

Support for Wechat applet，https://developers.weixin.qq.com/miniprogram/en/dev/

Support for Wechat applet

---

integration/test/ParseLiveQueryTest.js
src/LiveQueryClient.js
src/LiveQuerySubscription.js
src/ParseQuery.js
src/__tests__/LiveQueryClient-test.js
src/__tests__/ParseLiveQuery-test.js
src/__tests__/ParseQuery-test.js

Its a known issue that query.subscribe instantly returns a subscription without waiting until it subscribes. This PR fixes that.
This PR will make it easier to write Live Query tests on Parse Server.

Ensure LiveQuery subscribes

---

integration/test/ParseObjectTest.js
src/ParseObject.js

The new feature can be used to prevent cascade saving in nested objects (Only ignores objects that have already been saved previously):
```
parentObject.save(null, { cascadeSave: false });  // Child objects will not be saved (again)
```
Closes #864

feat(ParseObject): Add option `cascadeSave` to save()

---

integration/test/ParseUserTest.js
src/ParseUser.js

This is a follow-up to https://github.com/parse-community/Parse-SDK-JS/pull/756 to add the same functionality to `become`.
Let me know if there's anything I'm missing.

UserSubclass.become should return subclass

---

integration/test/ParseObjectTest.js
src/ParseObject.js
src/__tests__/ParseObject-test.js

Returns a promise boolean if the object exists on the server
See https://github.com/parse-community/parse-server/issues/5950

Support object.exists()

---

integration/test/ParseObjectTest.js
src/ParseObject.js

See parse-community/parse-server#5950

Support fetchAllIfNeededWithInclude

---

src/ParseQuery.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/917

(Docs) Query.limit remove maximum value

---

src/EventEmitter.js

This fix the crash when try to require EventEmitter on 0.61 react-native version
Related issue #936

Fix EventEmitter crash in react-native for v0.61.+ version

---

src/ParseObject.js
src/__tests__/ParseObject-test.js
src/__tests__/ParseQuery-test.js
src/__tests__/ParseUser-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/899, https://github.com/parse-community/Parse-SDK-JS/issues/955
Any advice or a different implementation would be appreciated.

Generate _localId as UUID

---

integration/test/ParseFileTest.js
src/ParseFile.js
src/Xhr.weapp.js
src/__tests__/ParseConfig-test.js
src/__tests__/ParseFile-test.js

Allow to cancel downloading file data or uploading via uri (uri is first downloaded to base64 then uploaded to the server).

Support Parse.File getData cancel

---

src/ParseSchema.js
src/__tests__/ParseSchema-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/941
Fixes Documentation.
`useMasterKey: true` is sent with every Parse.Schema request so passing it and sessionToken as a parameter is redundant.
https://github.com/parse-community/parse-server/blob/master/src/Routers/SchemasRouter.js#L124

Fix: Remove options from Parse.Schema

---

integration/test/ParseSchemaTest.js
src/ParseSchema.js
src/__tests__/ParseSchema-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/583
Let me know if there are any other tests needed.
I rarely use CLPs so I may miss something.

Set Class Level Permission via Parse.Schema

---

integration/test/ParseSchemaTest.js
package-lock.json
src/ParseSchema.js
src/__tests__/ParseFile-test.js
src/__tests__/ParseSchema-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/930
Requires Parse Server 3.7.0+
Feature: https://github.com/parse-community/parse-server/pull/5835
I added a FieldOption to addField and its counter parts. This will allow for future options like uppercase / lowercase for example.

Parse.Schema required fields and defaultValues

---

README.md
integration/test/ParseUserTest.js
src/AnonymousUtils.js
src/FacebookUtils.js
src/ParseUser.js
src/__tests__/AnonymousUtils-test.js
src/__tests__/FacebookUtils-test.js
src/__tests__/ParseUser-test.js
src/interfaces/AuthProvider.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/934
Addresses: https://github.com/parse-community/Parse-SDK-JS/issues/552
Adds deprecation for _linkWith and _loginWith
I can check the links works after this PR is merged.

Missing documentation for Custom Auth

---

src/ParseUser.js
src/__tests__/ParseUser-test.js

This is specifically for facebook since you can't register a auth provider in cloud code (FB doesn't exist).
Removes duplicate logic (linkWith handles the providers)
```
Cannot read property 'getAuthType' of undefined
```
Note: I can't add an integration test for this. I have tested and this works.
`integration/tests` uses /lib/node
`integration/server.js` uses /node_modules/parse (this doesn't have changes made in /lib/node)

Can unlink without provider (cloud code)

---

src/LiveQueryClient.js
src/ParseLiveQuery.js
src/__tests__/LiveQueryClient-test.js
src/__tests__/ParseLiveQuery-test.js

Adds reconnect for error event from server (already reconnects with web socket error).
Adds backwards compatibility for additionalProperties that do not exist in the server.
This PR will require a server update.
Use Case: Determine which client the live query request was sent from.
Will open a PR separately for the following.
```
subscription.on('create', (object, options) => {
options.installationId, options.clientId, etc
});
```

Add installationId to LiveQuery

---

integration/test/ParseLiveQueryTest.js
package-lock.json
src/LiveQueryClient.js
src/LiveQuerySubscription.js

Let me know if changes are needed.

Add options to LiveQuerySubscription

---

integration/test/ParseUserTest.js
src/ParseUser.js

@taivo Let me know if any changes can be made to replicate your issue

Properly store User Subclass in Storage

---

src/ParseQuery.js
src/__tests__/ParseQuery-test.js

Taken from Android API [fromNetwork()](http://parseplatform.org/Parse-SDK-Android/api/com/parse/ParseQuery.html#fromNetwork--)
Can be used to switch from localDatastore back to the server.

Support query.fromNetwork()

---

src/CoreManager.js
src/RESTController.js
src/__tests__/RESTController-test.js

Fixes: https://github.com/parse-community/Parse-SDK-JS/issues/1014
Feed back would be appreciated.

Support custom request headers

---

src/RESTController.js
src/Xhr.weapp.js
src/__tests__/RESTController-test.js
src/__tests__/test_helpers/mockXHR.js

* Add support for wechat
* Add length of data downloaded
* Add length of total data
https://developers.weixin.qq.com/miniprogram/en/dev/api/network/download/DownloadTask.onProgressUpdate.html
https://developer.mozilla.org/en-US/docs/Web/API/ProgressEvent
@kartheeknagasuri Can you try this?

Improve file upload progress

---

integration/test/ParseQueryTest.js
src/ParseQuery.js
src/RESTController.js
src/__tests__/ParseQuery-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1021, https://github.com/parse-community/Parse-SDK-JS/pull/1027
Moves abort event to prevent xhr.open from calling it.
Ensure requestTask is set after the request sends.
* Improves browser support

Support query.cancel() on Node

---

integration/test/ParseUserTest.js
src/ParseObject.js
src/__tests__/ParseUser-test.js

Fixes: https://github.com/parse-community/Parse-SDK-JS/issues/536
Parse.User.signUp actually does a ParseObject.save() at its core which does not send an installationId.
This is useful to prevent invalid session token and tests session clean up.

User signup with installationId

---

src/CoreManager.js
src/ParseObject.js
src/__tests__/Parse-test.js
src/__tests__/ParseObject-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1045
Currently the /batch endpoint send multiple requests in the with the number of objects equal to batchSize (default 20). I believe batchSize was added to reduce server load during the parse.com days. Having batchSize will make result in a certain amount of overhead for your client.
This PR will allow you to decrease the number of requests which may result in saving resources and faster requests.

Support global request batch size

---

src/ParseFile.js
src/ParseObject.js
src/RESTController.js
src/TaskQueue.js
src/__tests__/ParseFile-test.js
src/__tests__/ParseUser-test.js
src/__tests__/SingleInstanceStateController-test.js
src/promiseUtils.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1049
A small optimization with saving files in saveAll.
Clean up deferred promises.
@stevestencil Can you check and see if this works for you?
Let me know if anything else is needed.

Saving files with sessionToken

---

integration/test/ParseLiveQueryTest.js
src/LiveQueryClient.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1055
This PR just forces sessionToken null to be undefined when intializing the client.
If anybody knows how a sessionToken can be null instead of a string, '', or undefined, let me know.

Fix subscribing to null sessionToken

---

src/ParseObject.js
src/__tests__/ParseObject-test.js

Pull Request fixing issue #1063.
Add a check for ID definition before fetching data.

Throw error when fetching an object without ID

---

src/ParseUser.js
src/__tests__/ParseUser-test.js

It was hard to determine that `name` actually refer to `username`. Can we make it specific?

Change username signup error

---

src/ParseObject.js
src/__tests__/ParseObject-test.js

On SDK 2.11 saving new objects with option cascadeSave=false returns object without id (id = undefined). 
Rationale:
_handleSaveResponse -> _migrateId demands _localId AND serverId to be defined
_localId is generated with _getId()
normally _getId() is called in object.save() method by calling unsavedChildren()
but when cascadeSave=false unsavedChildren is not called -> _localId is undefined -> migrateId does not save serverId from created object
Solution:
since _localId is needed in controller.save() method, just call _getId() there

Fix cascadeSave=false bug

---

src/ParseQuery.js
src/__tests__/ParseQuery-test.js

These methods (`ParseQuery.map`, `ParseQuery.filter`, and `ParseQuery.reduce`) are documented as behaving similarly to `ParseQuery.each` (which they rely on under the hood): if the callback they are passed returns a promise, we should:
- wait for that promise to resolve before continuing iteration
- if that promise rejects, we should stop iteration and return a rejected promise
These methods weren't living up to that contract. Here's a series of adjustments to each one so that they follow those guidelines.

Make iteration query methods respect returned promises

---

src/ParseQuery.js
src/__tests__/ParseQuery-test.js

When a query has a large enough result set that we don't want to
materialize it at once, the SDK provides `query.each()`, which yields
each matching object to a processor, one at a time. This is a handy
tool, but if the number of records to process is really so large, we
also can take advantage of batching the processing. Compare the
following operations:
```js
// Processing N items involves N calls to Parse Server
new Parse.Query('Item').each((item) => {
item.set('foo', 'bar');
return item.save();
})
// Processing N items involves ceil(N / batchSize) calls to Parse Server
const batchSize = 200;
new Parse.Query('Item').eachBatch((items) => {
items.forEach(item => item.set('foo', 'bar'));
return Parse.Object.saveAll(items, { batchSize });
}, { batchSize });
```
The `.each()` method is …

Add `query.eachBatch()` to Parse.Query API

---

integration/test/ParseQueryTest.js

When running tests on my computer (running MongoDB 4.2.x), this test was
failing in a surprising way:
```
Failures:
1) Parse Query can use a regex with all modifiers
Message:
Uncaught exception: TypeError: message.split is not a function
Stack:
at <Jasmine>
```
This turns out to be because the error being returned has a `message`
attribute that is an object instead of a string. Catching and printing
the error shows us an object like this:
```
{ Error: [object Object]
at handleError (/Users/noahsilas/src/Parse-SDK-JS/lib/node/RESTController.js:380:17)
at process._tickCallback (internal/process/next_tick.js:68:7)
message:
{ ok: 0,
errmsg: 'Regular expression is invalid: missing )',
code: 51091,
codeName: 'Location51091',
name: 'MongoError' },
code: 1 }
```
Following up on this, we find a …

Fix integration tests on later MongoDB

---

package-lock.json
src/RESTController.js
src/__tests__/ParseFile-test.js
src/__tests__/RESTController-test.js
src/__tests__/test_helpers/mockXHR.js

Based on the discussion from [#1096](https://github.com/parse-community/Parse-SDK-JS/issues/1096)
Thanks to @ladigitale for the advice. :+1:

Fix file upload progress

---

src/ParseFile.js
src/RESTController.js
src/__tests__/ParseFile-test.js
src/__tests__/RESTController-test.js

According to @ladigitale from [last PR](https://github.com/parse-community/Parse-SDK-JS/pull/1133)
> I just found the time to test the pacth.
> As expected at the end of the upload with this code you will yet have 2 consecutive callbacks of the same function with different meanings :
> 
> 1 14535341 14535341 (meaning end of the upload)
> 1 165 165 (meaning end of the download sent as one chunk because of the low size of the response)
> 
> Thats why aditionnal imformations / api evolution would have been usefull.

Fix File Progress Type

---

src/ParseObject.js
src/RESTController.js
src/__tests__/ParseObject-test.js

Exposes the `context` object in `Parse.Object.save()` so that parameters can be made accessible in Cloud Code triggers `beforeSave`, `afterSave`.
Example:
```
const obj = new TestObject();
await obj.save(null, {context: {a: "a"}});
Parse.Cloud.beforeSave("TestObject", req => {
console.log(req.context.a);
});
Parse.Cloud.afterSave("TestObject", req => {
console.log(req.context.a);
});  
```
---
Don't merge until

add context to Parse.Object.save

---

integration/test/ParseLiveQueryTest.js
src/LiveQueryClient.js
src/__tests__/LiveQueryClient-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1147
Waits 200 milliseconds to allow for client to set open event after the subscription resolves.

Fix: Live Query Subscription Open Event

---

src/ParseQuery.js

Currently, what's happening with the `eachBatch` Query method is this:
- find X objects
- execute a callback on these objects
- find the next X objects
The issue is that while executing the callback, nothing is done, and we have to wait for the next Find to succeed to start again the callback.
An easy improvement is to launch the next query in parallel of the execution of the callback, so that when the callback is done, the next batch is already ready to be consumed (or more advanced if the query is longer than the callback execution)
It's done by changing the order of the promises, and waiting for both the query and the callback on the previous batch to be resolved.

Improve eachBatch method

---

src/RESTController.js

Removed deletion of context from save options to preserve it when cascade-saving child objects.
related to https://github.com/parse-community/parse-server/issues/6736

fix context when cascade-saving objects

---

src/ParseError.js

Adds new Parse Error 159: `DUPLICATE_REQUEST`.
This PR completes the server side implementation of https://github.com/parse-community/parse-server/pull/6748.

add idempotency error "duplicate request"

---

src/LiveQueryClient.js
src/__tests__/LiveQueryClient-test.js

Similar to https://github.com/parse-community/Parse-SDK-JS/pull/1151
Waits 200 milliseconds to allow for client to set error event after the subscription resolves.

Fix: Live Query Subscription Error Event

---

integration/test/ParseUserTest.js

I accidentally deleted the developer account used for testing. Changed the access keys to fix Twitter failing tests.

Fix User Linking tests

---

src/CloudCode.js

Hi all,
Not sure if my formatting is perfect but closes #1176 (removes pre. SDK 2.0 success functions), and adds documentation for LiveQuery triggers.
Also, for me, when I google "Parse Javascript SDK", it takes me to v1.11.0. Is there any way we can add "This SDK is outdated" or some other warning to point users to the latest SDK?
Thank you!

Update Cloud Code

---

integration/cloud/main.js
integration/server.js
integration/test/IdempotencyTest.js
integration/test/ParseQueryTest.js
integration/test/clear.js
package-lock.json
src/CoreManager.js
src/Parse.js
src/RESTController.js
src/__tests__/Parse-test.js
src/__tests__/RESTController-test.js
src/__tests__/test_helpers/mockXHR.js

Ref: https://github.com/parse-community/parse-server/issues/6744, https://github.com/parse-community/parse-server/pull/6748
Idempotency enforcement for client requests. This deduplicates requests where the client intends to send one request to Parse Server but due to network issues the server receives the request multiple times.
**Caution, this is an experimental feature that may not be appropriate for production.**
To enable use either of the following:
* `Parse.CoreManager.set('IDEMPOTENCY': true)`
* `Parse.idempotency = true`;
This PR addresses
* Add `X-Parse-Request-Id` uuid to the request.
* Improve xmlhttprequest error message handling
* Improve clearing of database after test
* Improve tests the require indexing

Support Idempotency

---

package.json

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1201
Moves crypto-js to optionalDependencies

fix: crypto-js crashing React Native

---

integration/test/ParseLocalDatastoreTest.js
src/LocalDatastore.js
src/ParseObject.js
src/ParseOp.js
src/__tests__/ParseObject-test.js
src/__tests__/encode-test.js
src/encode.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1118
Let me know if more tests are needed. Can be improved in the future.

fix(LocalDatastore): Allow Pin of unsaved Parse.Object

---

integration/test/ParseRelationTest.js
src/ParseRelation.js
src/__tests__/ParseRelation-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1217

fix(ParseRelation): Schema mismatch on empty array

---

integration/test/ParseQueryTest.js
src/ParseQuery.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1196

fix(ParseQuery): Select on null fields

---

integration/test/ParseQueryTest.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

To get around the 100 objects maximum retrieval on the Parse Server side I used to do `Parse.Query().limit(9999).find()`.
And after looking at the code I found out about the `eachBatch` method which is really neat and I wonder if you'd consider adding a `findAll` method the the Parse.Query class based on it.

Add a findAll method to ParseQuery

---

integration/test/ParseQueryTest.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

- Add possibility to pass objects to equalTo and notEqualTo
_@dplewis Please add hacktoberfest label_

equalTo + notEqualTo: Add possibility to pass objects

---

src/Parse.js

Addresses: https://github.com/parse-community/Parse-SDK-JS/issues/491
I've randomly seen users post about not being able to set the `serverURL`. It's usually typescript / web pack / babel issue with `defineProperty`.
https://parseopensource.slack.com/archives/C011ZF86LR2/p1600690460002100
Thoughts?

Improve initialization setters/getters

---

src/CoreManager.js
src/Push.js

* Enforce MasterKey
* Remove backbone style options
* Available only in Cloud Code

Improve Parse.Push Documentation

---

src/ParseGeoPoint.js
src/ParseObject.js
src/ParseQuery.js
src/ParseUser.js

Old backbone callbacks (options.success, options.error) are only used in linkWith authentication and object.set validation now.
i.e
```
object.set("currentPlayer", player2, {
error: function(objectAgain, error) {
// The set failed validation.
}
});
```

Remove backbone callback documentation

---

src/ParseObject.js
src/__tests__/ParseObject-test.js

Prevents `TypeError: Cannot read property 'id' of null`
Handles input the same way saveAll and destroyAll.
Also removed unnecessary LDS call on destroy all for non ParseObject / Array<ParseObject>
Let me know if I need to change anything.

fix(fetchAll): Properly handle passed in values

---

README.md

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1249
I'm not sure this is the best way to document how to add Parse SDK to a Project. There are many types of imports like CommonJS, RequireJS, es6 etc, not to mention the browser bundlers like Webpack, rollup that don't like certain imports.
@davimacedo @TomWFox

Document SDK module import

---

src/ParseOp.js

Addresses: https://github.com/parse-community/Parse-SDK-JS/issues/443
Removing this to prevent confusion. Does anybody want to explain why this is needed? Its been there since the beginning of the SDK

fix(AddUniqueOp): Remove unnecessary object reference and comment

---

integration/test/ParseQueryTest.js
package.json
src/__tests__/test_helpers/asyncHelper.js
src/__tests__/test_helpers/mockRNStorage.js
src/__tests__/test_helpers/mockWeChat.js
src/__tests__/test_helpers/mockXHR.js

Adding single quotes around the glob allows it to find subfolders in directories

Fix prettier

---

integration/test/ParseLiveQueryTest.js
src/LiveQueryClient.js

Fixes issue where optional field if null won't connect to the LiveQueryServer.
Fixes: https://github.com/parse-community/parse-server/pull/7099
See [LiveQuery Protocol Specification](https://github.com/parse-community/parse-server/wiki/Parse-LiveQuery-Protocol-Specification)

fix(LiveQuery): Allow connect with null fields

---

src/ParseFile.js
src/__tests__/ParseFile-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1272

Add useMasterKey option to Parse.File.destroy()

---

src/ParseACL.js

Original description didn't have type expression for a argument. 
before
```
@param other The other object to compare to
```
after
```
@param {ParseACL} other The other object's ACL to compare to
```

docs: update equals method in ParseACL

---

src/__tests__/ParseObject-test.js
src/__tests__/ParseQuery-test.js
src/decode.js

Not sure how often this error would occur, but if you try to create a `ParseObject` with `fromJSON` with a Date, the date field is returned as `{}`
[Related](https://github.com/parse-community/parse-server/issues/7082)
Evidently, this bug also affects the localDataStore tests as:
descending date order should be larger (newer) to smaller (older)
Obj1: createdAt: new Date('2018-08-10T00:00:00.000Z'),
Obj2: createdAt: new Date('2018-08-11T00:00:00.000Z'),
Obj3: createdAt: new Date('2018-08-12T00:00:00.000Z'),
So, this test:
```
q = new ParseQuery('Item');
q.descending('_created_at');
q.fromLocalDatastore();
results = await q.find();
```
Should return Obj3, Obj2, Obj1. Instead, it returns Obj1, Obj2, then Obj3.
If this doesn't make sense, if you change the order that the objects are loaded …

fromJSON: Return date if value is a date 

---

integration/test/ParseObjectTest.js
src/ParseObject.js
src/__tests__/ParseObject-test.js
src/__tests__/ParseQuery-test.js
src/decode.js

Currently, there is no way to save fields to a Parse.Object using `fromJSON`, as `dirtyKeys` doesn't get set.
This can be confusing as at first glance, you would expect the keys to be set as they are defined. However, after the object is fetched, the keys will be null.
```
it('from json save data', async (done) => {
const json = {
className : 'TestObject',
date: new Date(),
array: [],
object: {},
string: ''
}
const obj = Parse.Object.fromJSON(json);
expect(obj.get('date')).toBeDefined()
expect(obj.get('date')).toBeInstanceOf(Date);
expect(obj.get('array')).toBeDefined()
expect(obj.get('array')).toBeInstanceOf(Array);
expect(obj.get('object')).toBeDefined()
expect(obj.get('object')).toBeInstanceOf(Object);
expect(obj.get('string')).toBeDefined() …
```

Allow fromJSON to set keys to dirty

---

integration/test/ParseQueryTest.js
src/ParseQuery.js
src/__tests__/ParseQuery-test.js

Mimics [options](https://github.com/parse-community/parse-php-sdk/pull/423) in PHP SDK.
Works for get, find and first queries.

feat: Add option to return raw json from queries

---

src/ParseUser.js
src/__tests__/ParseUser-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1296
This addresses issues using AsyncStorage.
* Introduces new `user.isCurrentAsync` function

fix: User management on React-Native

---

README.md
integration/test/helper.js
package-lock.json
package.json
src/IndexedDBStorageController.js
src/Parse.js
src/__tests__/Parse-test.js
src/__tests__/Storage-test.js
src/__tests__/test_helpers/mockIndexedDB.js
src/__tests__/test_helpers/mockStorageInteface.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1270
```js
Parse.CoreManager.setStorageController(Parse.IndexedDB);
```
The goal of this PR is to provide a default indexedDB implementation. Users are more than welcome to create their own storage controllers if they need transactions, indexes or schema migration etc...
Uses the lightweight, [idb-keyval](https://github.com/jakearchibald/idb-keyval) package instead of the full [idb](https://www.npmjs.com/package/idb)
@FunMiles Can you give it a try?

feat: Add IndexedDB Storage Controller

---

integration/test/ParsePushTest.js
integration/test/helper.js
src/Push.js
src/RESTController.js
src/__tests__/Cloud-test.js
src/__tests__/RESTController-test.js

Similar to how jobStatus is handled.
* Parse.Push.send now returns the pushStatusId
* Add useMasterKey to Parse.Push.send
* Add new Parse.Push.getPushStatus
* Add new Push Integration tests.
```
const pushStatusId = await Parse.Push.send(payload);
const pushStatus = await Parse.Push.getPushStatus(pushStatusId);
```
This is currently a breaking change. Parse.Push.send returned `{ result: true }` before.

Support PushStatus on Parse.Push

---

integration/test/ParseQueryTest.js
src/ParseQuery.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1304

Add modifiers to startsWith / endsWith

---

src/Parse.js
src/__tests__/Parse-test.js

Adds `Parse.getServerHealth` as a quick way to check on the server health without having to make an arbitrary request to a functional endpoint, and without needing keys.
Similar to the PHP SDK
https://github.com/parse-community/parse-php-sdk/pull/366

Add Server Health Check

---

src/EventuallyQueue.js
src/__tests__/EventuallyQueue-test.js

The `/health` endpoint has been supported on the server since 2.2.5.
This fixes an issue where a `403` would let us know that server was online.

fix(EventuallyQueue): Poll against /health endpoint

---

integration/test/ParseObjectTest.js
src/ParseObject.js
src/__tests__/ParseObject-test.js

Calling increment on a field that doesn't exists (serverData stored in object state) gets ignored.
```
const obj = new TestObject();
obj.increment('a.b.c.d'); // ignored
await obj.save();
```
I believe this was ignored because the server doesn't support it and throws the following error
```
Unhandled promise rejection: TypeError: Cannot read property 'split' of undefined
```

Allow nested increment on undefined fields

---

integration/test/ParseObjectTest.js
src/CoreManager.js
src/Parse.js
src/ParseObject.js
src/__tests__/Parse-test.js
src/__tests__/ParseObject-test.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1097
Ref: https://github.com/parse-community/parse-server/pull/6177
@JeromeDeLeon

feat: Allow saving with custom objectId

---

CHANGELOG.md
package-lock.json
package.json

A 403 forbidden side effect was introduced in 3.0.0. Has been addressed in this release.
https://community.parseplatform.org/t/js-sdk-3-0-0-parse-initialize-forbidden/1363
There were a number of fixes and improvements over the last week that is included in this release.

⚡️ Release 3.1.0

---

CHANGELOG.md
integration/test/ParseSubclassTest.js
src/ParseObject.js
src/__tests__/ParseObject-test.js

Hi,
Let's say you want to create a global function `getName` on all your Parse.Objects. Let's say you have 4 different classes. Here's how you'd have to do that now:
```javascript
class ClassOne extends Parse.Object {
constructor() {
super('ClassOne');
}
getDetails() {
return `${this.get('title')} ${this.get('description')}`;
}
}
class ClassTwo extends Parse.Object {
constructor() {
super('ClassTwo');
}
getDetails() {
return `${this.get('title')} ${this.get('description')}`;
}
}
class ClassThree extends Parse.Object {
constructor() {
super('ClassThree');
}
getDetails() {
return `${this.get('title')} ${this.get('description')}`;
}
}
Parse.Object.registerSubclass('ClassOne', ClassOne);
Parse.Object.registerSubclass('ClassTwo', ClassTwo);
Parse.Object.registerSubclass('ClassThree', …
```

new: className in subclass constructor

---

integration/test/ParseCloudTest.js
integration/test/ParseEventuallyQueueTest.js
integration/test/ParseGeoPointTest.js
integration/test/ParseLocalDatastoreTest.js
integration/test/ParseServerTest.js
integration/test/ParseSubclassTest.js
integration/test/ParseUserTest.js
integration/test/helper.js
jasmine.json
src/ParseObject.js
src/__tests__/ParseObject-test.js

Allowing the test suite to run in a random order will help find test passes only based on a previously ran test.
* Adds new `Parse.Object.unregisterSubclass` feature
* Properly closes test created servers
* Generate unique username and password for user tests
* Properly handle unsorted queries (results returned in random order)
* Improve tests with background operations
* Remove setTimeout when possible

Enable integration tests to be randomized

---

src/AnonymousUtils.js
src/ParseUser.js
src/__tests__/ParseUser-test.js

Based on conversation [here](https://community.parseplatform.org/t/anonymous-user-destroyed-on-logout/1425/6)
* Remove deletion on logout
* Remove deletion on setCurrentUser
* Exposes registered on AnonymousUtils

Remove deletion of Anonymous User on logout

---

src/ParseQuery.js

Closes: https://github.com/parse-community/Parse-SDK-JS/issues/1336

(docs): Improve IncludeAll description

---

CHANGELOG.md
integration/test/helper.js
package-lock.json
package.json

Small release nothing too major (pun intended)

⚡️ Release 3.2.0

---

src/ParseError.js

See parse-community/parse-server#7331
This PR adds a new error code for geospatial index failures. MongoDB returns the error codes 16755/16756 if one tries to create an object on a collection with a geospatial index (such as `2dsphere`) but MongoDB fails to index the object, perhaps because the geojson is invalid or the index does not support the given geometry.

Added an error code for geospatial index failures

---

.github/workflows/ci.yml

Adds a CI check that requires `package-lock.json` to be generated with npm <7.
Building with npm 7 causes errors that are difficult to interpret.
The discussion in https://github.com/parse-community/Parse-SDK-JS/pull/1344 shows that without a clear error message, contributors and reviewers unnecessarily spend more time to trace the issue back to npm 7.
This is analogous to https://github.com/parse-community/parse-server/pull/7333.

Add npm version ci check

---

src/ParseObject.js

added an example in the Parse.Object docs to show usage of saving a single attribute on a parse object. Users may use this in typescript class extensions of Parse.Object as a class attribute mutator.

doc improvement

---

src/EventEmitter.js
src/__tests__/react-native-test.js

fix EventEmitter undefined on React Native 0.64

---

integration/test/ParseObjectTest.js
integration/test/ParseUserTest.js
src/ObjectStateMutations.js
src/ParseObject.js
src/__tests__/ParseObject-test.js

Improve support for nested keys

---

src/EventEmitter.js
src/__tests__/react-native-test.js

Improve https://github.com/parse-community/Parse-SDK-JS/pull/1351

Fix react native build

---

.github/ISSUE_TEMPLATE/---1-report-an-issue.md
.github/ISSUE_TEMPLATE/---2-feature-request.md
.github/pull_request_template.md

- Added PR template according to our best practice templates
- Updated FR template according to our best practice templates

Improve GH templates

---

CONTRIBUTING.md

Markdown formats `__test__` as __test__ (bold, no underscores).
Related issue: #1409
Escape the underscores like so: `\_\_test\_\_`.
None: this is a minor documentation change.

CONTRIBUTING.md: Escape the underscores in "__test__"

---

src/__tests__/OfflineQuery-test.js

Adding missing test cases from https://github.com/parse-community/Parse-SDK-JS/pull/1344
Will add to the server for LiveQuery.
Related issue: #`FILL_THIS_OUT`

chore(LDS): Improve $relativeTime tests

---

CHANGELOG.md
package-lock.json
package.json

crypto-js 4.0.0 requires manual polyfill when used with webpack 5 in Parse Dashboard, see https://github.com/brix/crypto-js/pull/364.
Related issue: https://github.com/parse-community/parse-dashboard/pull/1807#issuecomment-926921625
Bump crypto-js to 4.1.1, which should fix the issue.

fix: bump crypto js
